### ISSUE TITLE
Exception when starting wollok game.

### ISSUE THREAD

**Issue by npasserini** [wollok/granja-de-orson-game#2]
I am using #dev branch of wollok, so wollok v1.6 (to be). Is there any incompatibility?
Could we make this work in v.1.6?

wollok.lang.MessageNotUnderstoodException: game[] does not understand setTitle(p0)
    at wollok.lang.Object.messageNotUnderstood(name,parameters) [/lang.wlk:218]
    at nivel.nivel.configurate() [/nivel.wlk:16]
    at  [/nivel.wlk:12]

**Comment by PalumboN** [comment]
In last Wollok version we update de accessors methods for game and position objects with new convention: without 'get' & 'set' words.

So you should do something like game.title("WGTitle")

**Comment by fdodino** [comment]
Lo cerré porque pasó mucha agua bajo el puente...
